# Generated by Django 4.1.2 on 2022-12-11 06:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaRevs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=90)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=90)),
                ('password', models.CharField(max_length=40)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Films',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='nombre',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='texto',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='fecha',
            new_name='date',
        ),
        migrations.AddField(
            model_name='reviews',
            name='film',
            field=models.CharField(default=datetime.datetime.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
