# Generated by Django 4.1.2 on 2022-12-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaRevs', '0003_avatar_delete_user_reviews_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='images',
            new_name='image',
        ),
    ]
