# Generated by Django 4.1.2 on 2022-12-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaRevs', '0006_alter_reviews_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='body',
        ),
    ]
