# Generated by Django 4.1.2 on 2022-12-13 18:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaRevs', '0007_remove_reviews_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
